# Generated by Django 5.0.7 on 2024-08-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinta_id', models.IntegerField()),
                ('sinta_code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('abbrev', models.CharField(blank=True, max_length=255, null=True)),
                ('total_department', models.IntegerField(blank=True, null=True)),
                ('total_author', models.IntegerField(blank=True, null=True)),
                ('total_journal', models.IntegerField(blank=True, null=True)),
                ('total_document_scopus', models.IntegerField(blank=True, null=True)),
                ('total_document_gsholar', models.IntegerField(blank=True, null=True)),
                ('total_document_wos', models.IntegerField(blank=True, null=True)),
                ('total_document_garuda', models.IntegerField(blank=True, null=True)),
                ('total_citation_scopus', models.IntegerField(blank=True, null=True)),
                ('total_citation_gsholar', models.IntegerField(blank=True, null=True)),
                ('total_citation_wos', models.IntegerField(blank=True, null=True)),
                ('total_citation_garuda', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
