# Generated by Django 5.0.7 on 2024-08-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='sinta_id',
            field=models.IntegerField(unique=True),
        ),
    ]
