# Generated by Django 5.0.7 on 2024-08-21 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinta', '0002_alter_university_sinta_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinta_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('gsholar_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('editor_url', models.URLField(blank=True, null=True)),
                ('pissn', models.CharField(blank=True, max_length=255, null=True)),
                ('eissn', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('accredited', models.CharField(blank=True, max_length=255, null=True)),
                ('scopus', models.CharField(blank=True, max_length=255, null=True)),
                ('garuda_url', models.URLField(blank=True, null=True)),
                ('impact', models.CharField(blank=True, max_length=255, null=True)),
                ('h5_index', models.CharField(blank=True, max_length=255, null=True)),
                ('citation_5y', models.CharField(blank=True, max_length=255, null=True)),
                ('citation', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('garuda_description', models.TextField(blank=True, null=True)),
                ('garuda_image_url', models.URLField(blank=True, null=True)),
                ('garuda_subject', models.TextField(blank=True, null=True)),
                ('aruna_subject', models.TextField(blank=True, null=True)),
                ('doi_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sinta.university')),
            ],
        ),
    ]
