# Generated by Django 5.0.7 on 2024-08-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinta', '0003_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='total_document',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garuda_id', models.IntegerField(unique=True)),
                ('garuda_url', models.URLField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.JSONField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('gsholar_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('doi_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('total_journal_document', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sinta.journal')),
            ],
        ),
    ]
