# Generated by Django 5.0.7 on 2024-08-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinta', '0004_journal_total_document_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='author_guideline_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
