# Generated by Django 5.0.7 on 2024-09-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinta', '0005_journal_author_guideline_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=600, null=True),
        ),
    ]
